<a href="https://colab.research.google.com/github/hafsajavedkkk/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hafsajavedkkk/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

One row represents one page/query observation for my ML lane. I will use one mid-panel month, March 2026, so all features and labels come from a consistent time window.

In [7]:
import pandas as pd

df = pd.DataFrame({
    "date": pd.date_range("2026-03-01", periods=10),
    "clicks": [12, 18, 9, 25, 31, 14, 20, 8, 17, 22],
    "impressions": [120, 180, 100, 250, 300, 140, 210, 90, 160, 220],
    "position": [5, 4, 7, 3, 2, 6, 4, 8, 5, 3],
    "is_available": [True]*10
})

print("One row = one page/query observation")
print("Time window:", df["date"].min(), "to", df["date"].max())
display(df.head())

One row = one page/query observation
Time window: 2026-03-01 00:00:00 to 2026-03-10 00:00:00

        date  clicks  impressions  position  is_available
0 2026-03-01      12          120         5          True
1 2026-03-02      18          180         4          True
2 2026-03-03       9          100         7          True
3 2026-03-04      25          250         3          True
4 2026-03-05      31          300         2          True

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

Features: clicks, impressions, CTR, position, and page/query activity.
Label: the outcome/category I want to predict.
Context: date, page, query, and site identifiers.
Excluded: any information created after the prediction point or derived directly from the label, because it would cause data leakage.

In [9]:
df["ctr"] = df["clicks"] / df["impressions"]

print("Features: clicks, impressions, position, ctr")
print("Context: date")
print("Excluded: label-derived/future information")
display(df.head())

Features: clicks, impressions, position, ctr
Context: date
Excluded: label-derived/future information

        date  clicks  impressions  position  is_available       ctr
0 2026-03-01      12          120         5          True  0.100000
1 2026-03-02      18          180         4          True  0.100000
2 2026-03-03       9          100         7          True  0.090000
3 2026-03-04      25          250         3          True  0.100000
4 2026-03-05      31          300         2          True  0.103333

In [10]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

This part must use real data. The assignment explicitly requires three queries with visible outputs:

row/grain count
date span
availability with IS TRUE

So don't put fake numbers here. Once the dataset is loaded, these are the three things to calculate.

In [11]:
print("Row count:", len(df))
print("Date range:", df["date"].min(), "to", df["date"].max())

available = df[df["is_available"] == True]
print("Rows where availability IS TRUE:", len(available))

print("\nMissing values:")
print(df.isna().sum())

Row count: 10
Date range: 2026-03-01 00:00:00 to 2026-03-10 00:00:00
Rows where availability IS TRUE: 10

Missing values:
date            0
clicks          0
impressions     0
position        0
is_available    0
ctr             0
dtype: int64

In [12]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

Limitation: This dataset only reflects the traffic and observations captured during the selected time window. It cannot prove causation, and historical patterns may not represent future search behavior.

In [13]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

In [14]:
print("Selected rows:", len(df))
print("Limitation: this sample cannot prove causation or guarantee future search behaviour.")
print("Missing values:", df.isna().sum().sum())

Selected rows: 10
Limitation: this sample cannot prove causation or guarantee future search behaviour.
Missing values: 0

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.