<a href="https://colab.research.google.com/github/hafsajavedkkk/flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-10 — Content Action Playbook

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hafsajavedkkk/flyrank-ml-internship/blob/main/work/notebooks/w07_action_playbook.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Ranked actions + reason codes

*The queue: what to do first, and why, in words a human trusts.*

I rank opportunities by priority score. High-impression items with weak click performance receive the highest priority because they already have visibility but may have room for improvement. Each recommendation includes a reason code so a human can understand why it was selected.

In [1]:
import pandas as pd

queue = pd.DataFrame({
    "item": ["Page A", "Page B", "Page C", "Page D", "Page E"],
    "score": [0.92, 0.84, 0.76, 0.61, 0.48],
    "reason_code": [
        "HIGH_IMPRESSIONS_LOW_CTR",
        "HIGH_IMPRESSIONS_LOW_CTR",
        "POSITION_OPPORTUNITY",
        "POSITION_OPPORTUNITY",
        "MONITOR"
    ],
    "action": [
        "Optimize title/content",
        "Improve search snippet",
        "Review content",
        "Review content",
        "Monitor"
    ]
})

queue = queue.sort_values("score", ascending=False)
display(queue)

     item  score               reason_code                  action
0  Page A   0.92  HIGH_IMPRESSIONS_LOW_CTR  Optimize title/content
1  Page B   0.84  HIGH_IMPRESSIONS_LOW_CTR  Improve search snippet
2  Page C   0.76      POSITION_OPPORTUNITY          Review content
3  Page D   0.61      POSITION_OPPORTUNITY          Review content
4  Page E   0.48                   MONITOR                 Monitor

In [2]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Intended use and limits

*Who uses this, for what — and where it stops being valid.*

This playbook is intended to help a content or SEO reviewer prioritize what to inspect first. It provides decision support, not automatic publishing decisions. Scores are based on observed historical patterns and may become less reliable when traffic or search behaviour changes.

In [3]:
print("Intended use: prioritize items for human review.")
print("Limit: recommendations are decision-support, not automatic actions.")
print("Cost/value: review highest-ranked items first to focus limited time.")

Intended use: prioritize items for human review.
Limit: recommendations are decision-support, not automatic actions.
Cost/value: review highest-ranked items first to focus limited time.

In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Human review + the no-go list

*What a person must check before acting. What should never be automated.*

A human must verify the page context, data quality, business relevance, and recommendation before taking action. The system should never automatically delete content, publish changes, modify important pages, or treat a model score as proof that an action will work.

In [5]:
human_checks = [
    "Verify data quality",
    "Review page context",
    "Confirm business relevance",
    "Approve recommendation"
]

no_go = [
    "Automatic publishing",
    "Automatic deletion",
    "Changing important pages without approval",
    "Treating predictions as guaranteed outcomes"
]

print("Human checks:", human_checks)
print("Never automate:", no_go)

Human checks: ['Verify data quality', 'Review page context', 'Confirm business relevance', 'Approve recommendation']
Never automate: ['Automatic publishing', 'Automatic deletion', 'Changing important pages without approval', 'Treating predictions as guaranteed outcomes']

In [6]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Monitoring / retrain triggers

*What would tell you the recommendations went stale?*

I would monitor recommendation quality over time. A major drop in accuracy, large changes in feature distributions, new search behaviour, or repeated incorrect recommendations would indicate that the model may be stale and should be reviewed or retrained.

In [7]:
retrain_triggers = {
    "accuracy_below": 0.70,
    "major_data_drift": True,
    "repeated_bad_recommendations": True
}

print("Monitoring / retrain triggers:")
for trigger, value in retrain_triggers.items():
    print(trigger, ":", value)

Monitoring / retrain triggers:
accuracy_below : 0.7
major_data_drift : True
repeated_bad_recommendations : True

In [8]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 5. Exports for the paper

*Write the queue (and any figures you want to reuse) to work/outputs/ — your paper builds on these files.*

I export the ranked recommendation queue so it can be reused in the final research paper and reviewed independently of the notebook.

In [9]:
import os

os.makedirs("work/outputs", exist_ok=True)

output_path = "work/outputs/action_playbook_queue.csv"
queue.to_csv(output_path, index=False)

print("Exported:", output_path)
display(queue)

Exported: work/outputs/action_playbook_queue.csv

     item  score               reason_code                  action
0  Page A   0.92  HIGH_IMPRESSIONS_LOW_CTR  Optimize title/content
1  Page B   0.84  HIGH_IMPRESSIONS_LOW_CTR  Improve search snippet
2  Page C   0.76      POSITION_OPPORTUNITY          Review content
3  Page D   0.61      POSITION_OPPORTUNITY          Review content
4  Page E   0.48                   MONITOR                 Monitor

In [10]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.